spring:
  application:
    name: Net Service
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: url
    username: username
    password: password
